### PR TITLE
AppData: Add launchable tag

### LINKED ISSUE #172: [ninja test] fails
**OS:** Fedora 64-bit

Hello. Thanks to fix for issue _166_, now `meson build --prefix=/usr` succeeds. When it comes to `cd build; ninja test`, the test fails –[easyssh_ninja_test.txt](https://github.com/muriloventuroso/easyssh/files/10296140/easyssh_ninja_test.txt). Thus the program can't be installed.

### PR DESCRIPTION
**Pull request by ryonakano**
Fixes #172

@Ricky-Tigg Does this branch work for you?

### CODE REVIEW

**Comment by ryonakano** [comment]
I tested this branch on Fedora 37 and worked for me at least:

```
[user@fedora build]$ ninja test
[0/1] Running all tests.
1/2 Validate desktop file        OK              0.03s
2/2 Validate appdata file        OK              3.60s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /home/user/easyssh/build/meson-logs/testlog.txt
```

スクリーンショット 2022-12-24 13 21 51

**Comment by Ricky-Tigg** [comment]
```
$ ninja test
[200/222] Compiling Vala source Config...ksPopover.vala ../src/Widgets/Tab.vala
../src/Widgets/TerminalWidget.vala:175.21-175.35: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
  175 |                     this.spawn_sync(Vte.PtyFlags.DEFAULT, null, {"/bin/sh"},
      |                     ^~~~~~~~~~~~~~~                                         
../src/Widgets/TerminalWidget.vala:185.25-185.39: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
  185 |                         this.spawn_sync (Vte.PtyFlags.DEFAULT, dir, { shell },
      |                         ^~~~~~~~~~~~~~~                                       
../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: `Vte.Terminal.search_set_gregex' has been deprecated since 0.46
   97 |                     term.search_set_gregex (regex, 0);
      |                     ^~~~~~~~~~~~~~~~~~~~~~            
../src/MainWindow.vala:472.13-472.82: warning: unhandled error `GLib.SpawnError'
  472 |             Process.spawn_command_line_async (default_filemanager + " " + command);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
../src/MainWindow.vala:233.13-236.41: warning: unhandled error `GLib.SpawnError'
  233 |             var result = Process.spawn_command_line_sync ("xdg-mime query default inode/directory",
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  234 |                                     out stdout,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  235 |                                     out stderr,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  236 |                                     null);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
../src/MainWindow.vala:243.13-246.41: warning: unhandled error `GLib.SpawnError'
  243 |             var res = Process.spawn_command_line_sync ("cat /usr/share/applications/" + filename,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  244 |                                     out stdout,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  245 |                                     out stderr,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  246 |                                     null);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
Compilation succeeded - 6 warning(s)
[221/222] Running all tests.
1/2 Validate desktop file        OK              0.03s
2/2 Validate appdata file        OK              4.16s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```
The application fails to launch; `com.github.muriloventuroso.easyssh`  is endlessly prosecced. No  output while prosessing.

**Comment by Ricky-Tigg** [comment]
session: Wayland
```
$ ninja test
[200/222] Compiling Vala source Config...ksPopover.vala ../src/Widgets/Tab.vala
../src/Widgets/TerminalWidget.vala:175.21-175.35: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
  175 |                     this.spawn_sync(Vte.PtyFlags.DEFAULT, null, {"/bin/sh"},
      |                     ^~~~~~~~~~~~~~~                                         
../src/Widgets/TerminalWidget.vala:185.25-185.39: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
  185 |                         this.spawn_sync (Vte.PtyFlags.DEFAULT, dir, { shell },
      |                         ^~~~~~~~~~~~~~~                                       
../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: `Vte.Terminal.search_set_gregex' has been deprecated since 0.46
   97 |                     term.search_set_gregex (regex, 0);
      |                     ^~~~~~~~~~~~~~~~~~~~~~            
../src/MainWindow.vala:472.13-472.82: warning: unhandled error `GLib.SpawnError'
  472 |             Process.spawn_command_line_async (default_filemanager + " " + command);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
../src/MainWindow.vala:233.13-236.41: warning: unhandled error `GLib.SpawnError'
  233 |             var result = Process.spawn_command_line_sync ("xdg-mime query default inode/directory",
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  234 |                                     out stdout,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  235 |                                     out stderr,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  236 |                                     null);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
../src/MainWindow.vala:243.13-246.41: warning: unhandled error `GLib.SpawnError'
  243 |             var res = Process.spawn_command_line_sync ("cat /usr/share/applications/" + filename,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  244 |                                     out stdout,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  245 |                                     out stderr,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  246 |                                     null);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
Compilation succeeded - 6 warning(s)
[221/222] Running all tests.
1/2 Validate desktop file        OK              0.03s
2/2 Validate appdata file        OK              4.16s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```
session: X11
```
$ ninja test
[0/1] Running all tests.
1/2 Validate desktop file        OK              0.03s
2/2 Validate appdata file        OK              4.48s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```
IN both sessions the application fails to launch; `com.github.muriloventuroso.easyssh`  is endlessly prosecced. No  output while prosessing.

**Comment by Ricky-Tigg** [comment]
session: Wayland
```
$ ninja test
[200/222] Compiling Vala source Config...ksPopover.vala ../src/Widgets/Tab.vala
../src/Widgets/TerminalWidget.vala:175.21-175.35: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
  175 |                     this.spawn_sync(Vte.PtyFlags.DEFAULT, null, {"/bin/sh"},
      |                     ^~~~~~~~~~~~~~~                                         
../src/Widgets/TerminalWidget.vala:185.25-185.39: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
  185 |                         this.spawn_sync (Vte.PtyFlags.DEFAULT, dir, { shell },
      |                         ^~~~~~~~~~~~~~~                                       
../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: `Vte.Terminal.search_set_gregex' has been deprecated since 0.46
   97 |                     term.search_set_gregex (regex, 0);
      |                     ^~~~~~~~~~~~~~~~~~~~~~            
../src/MainWindow.vala:472.13-472.82: warning: unhandled error `GLib.SpawnError'
  472 |             Process.spawn_command_line_async (default_filemanager + " " + command);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
../src/MainWindow.vala:233.13-236.41: warning: unhandled error `GLib.SpawnError'
  233 |             var result = Process.spawn_command_line_sync ("xdg-mime query default inode/directory",
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  234 |                                     out stdout,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  235 |                                     out stderr,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  236 |                                     null);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
../src/MainWindow.vala:243.13-246.41: warning: unhandled error `GLib.SpawnError'
  243 |             var res = Process.spawn_command_line_sync ("cat /usr/share/applications/" + filename,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  244 |                                     out stdout,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  245 |                                     out stderr,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  246 |                                     null);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
Compilation succeeded - 6 warning(s)
[221/222] Running all tests.
1/2 Validate desktop file        OK              0.03s
2/2 Validate appdata file        OK              4.16s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```
session: X11
```
$ ninja test
[0/1] Running all tests.
1/2 Validate desktop file        OK              0.03s
2/2 Validate appdata file        OK              4.48s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```
In both sessions the application fails to launch; `com.github.muriloventuroso.easyssh`  is endlessly prosecced. No  output while prosessing.

**Comment by Ricky-Tigg** [comment]
sessions: Wayland and x11
```
$ ninja test
[200/222] Compiling Vala source Config...ksPopover.vala ../src/Widgets/Tab.vala
../src/Widgets/TerminalWidget.vala:175.21-175.35: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
  175 |                     this.spawn_sync(Vte.PtyFlags.DEFAULT, null, {"/bin/sh"},
      |                     ^~~~~~~~~~~~~~~                                         
../src/Widgets/TerminalWidget.vala:185.25-185.39: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
  185 |                         this.spawn_sync (Vte.PtyFlags.DEFAULT, dir, { shell },
      |                         ^~~~~~~~~~~~~~~                                       
../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: `Vte.Terminal.search_set_gregex' has been deprecated since 0.46
   97 |                     term.search_set_gregex (regex, 0);
      |                     ^~~~~~~~~~~~~~~~~~~~~~            
../src/MainWindow.vala:472.13-472.82: warning: unhandled error `GLib.SpawnError'
  472 |             Process.spawn_command_line_async (default_filemanager + " " + command);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
../src/MainWindow.vala:233.13-236.41: warning: unhandled error `GLib.SpawnError'
  233 |             var result = Process.spawn_command_line_sync ("xdg-mime query default inode/directory",
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  234 |                                     out stdout,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  235 |                                     out stderr,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  236 |                                     null);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
../src/MainWindow.vala:243.13-246.41: warning: unhandled error `GLib.SpawnError'
  243 |             var res = Process.spawn_command_line_sync ("cat /usr/share/applications/" + filename,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  244 |                                     out stdout,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  245 |                                     out stderr,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  246 |                                     null);
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
Compilation succeeded - 6 warning(s)
[221/222] Running all tests.
1/2 Validate desktop file        OK              0.03s
2/2 Validate appdata file        OK              4.16s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0
```
In both sessions the application fails to launch; `com.github.muriloventuroso.easyssh`  is endlessly processed. No  output while processing.

**Comment by ryonakano** [comment]
@Ricky-Tigg Hmm, I tested on Fedora 37 (x86_64) on VirtualBox but it launches as expected:

VirtualBox_Fedora 37_14_01_2023_11_07_05

I took the screenshot above on Wayland GNOME but the app also launches on X org. session too.

**Comment by Ricky-Tigg** [comment]
Well, the only certitude then, is that our system configurations must differ from each other.
```
$ dnf -q rq --installed --archlist noarch,x86_64 --qf '%{name} %{version}' gnupg2 gtk3 {granite,gtk3,json-glib,libgee06,vte291}-devel meson vala vte291 | column
gnupg2 2.3.8		libgee06-devel 0.6.8
granite-devel 6.2.0	meson 0.63.3
gtk3 3.24.36		vala 0.56.3
gtk3-devel 3.24.36	vte291 0.70.2
json-glib-devel 1.6.6	vte291-devel 0.70.2
```
My intention to obtain a back-trace by using `gdb` can't be put in practice since the debugging `run` freezes at the following line in regard to `Downloading 0.79 MB separate debug info for /usr/lib64/gvfs/libgvfscommon.so`. I guess you achieved your successful attempt in a VM with default configuration, excepting some of the above mentioned component that have to be manually installed

**Comment by Ricky-Tigg** [comment]
Well, the only certitude then, is that our system configurations must differ from each other.
```
$ dnf -q rq --installed --archlist noarch,x86_64 --qf '%{name} %{version}' gnupg2 gtk3 {granite,gtk3,json-glib,libgee06,vte291}-devel meson vala vte291 | column
gnupg2 2.3.8		libgee06-devel 0.6.8
granite-devel 6.2.0	meson 0.63.3
gtk3 3.24.36		vala 0.56.3
gtk3-devel 3.24.36	vte291 0.70.2
json-glib-devel 1.6.6	vte291-devel 0.70.2
```
My intention to obtain a back-trace by using `gdb` can't be put in practice since the debugging `run` freezes at the following line in regard to `Downloading 0.79 MB separate debug info for /usr/lib64/gvfs/libgvfscommon.so`. I guess you achieved your successful attempt with Fedora Desktop with default configuration, excepting of course some of the above mentioned component that have to be manually installed

**Comment by Ricky-Tigg** [comment]
Well, the only certitude then, is that our system configurations must differ from each other.
```
$ dnf -q rq --installed --archlist noarch,x86_64 --qf '%{name} %{version}' gnupg2 gtk3 {granite,gtk3,json-glib,libgee06,vte291}-devel meson vala vte291 | column
gnupg2 2.3.8		libgee06-devel 0.6.8
granite-devel 6.2.0	meson 0.63.3
gtk3 3.24.36		vala 0.56.3
gtk3-devel 3.24.36	vte291 0.70.2
json-glib-devel 1.6.6	vte291-devel 0.70.2
```
My intention to obtain a back-trace by using `gdb` can't be put in practice since `run` freezes at the following line in regard to `Downloading 0.79 MB separate debug info for /usr/lib64/gvfs/libgvfscommon.so`. I guess you achieved your successful attempt with Fedora Desktop with default configuration, excepting of course some of the above mentioned component that have to be manually installed

**Pull request merged**
