### PR TITLE
Updated spanish translation

### PR DESCRIPTION
**Pull request by AlonsoLP**
Hi.

Spanish translation complete.

Best regards.

### CODE REVIEW

**Comment by muriloventuroso** [comment]
Thanks for the collaboration. We use Weblate to facilitate the translation of this project. Join us there! https://hosted.weblate.org/engage/easyssh/

**Comment by AlonsoLP** [comment]
Joined! ;) Thanks.

**Comment by majko96** [comment]
So if I make slovak translation through weblate where it will be commited here?

**Comment by muriloventuroso** [comment]
Weblate will commit using your GitHub user automatically.

**Comment by majko96** [comment]
but I made translation 3 days ago and nothing was commited

**Comment by muriloventuroso** [comment]
ready!

**Comment by majko96** [comment]
So in next release will be my translation, yes? :) Thx

**Comment by muriloventuroso** [comment]
Already is your translation, was sent with your user. Weblate delays these submissions a bit, to be able to do review, etc. Thanks!

**Pull request merged**
